---
- name: mkdir -pv ~/dotfiles
  file: path=~/dotfiles state=directory

- name: remove old backup files ~/dotfiles/*~
  file: path={{ item }} state=absent
  with_fileglob:
    - ~/dotfiles/*~

- name: Check tmux verson
  command: tmux -V
  register: tmux_version
  tags:
    - base

- name: Add as Fact for tmux version
  set_fact:
    version: "{{ tmux_version.stdout.strip().split()[1] }}"
  tags:
    - base

- debug: var=tmux_version.stdout_lines
  when: test | default(false) | bool

- debug: var=tmux_version.stdout.strip()
  when: test | default(false) | bool

- debug: var=tmux_version.stdout.strip().split()[1]
  when: test | default(false) | bool

- debug: var=version
  when: test | default(false) | bool

- name: Check emacs verson
  shell: emacs --version|head -n 1|awk '{print $3}'
  register: emacs_version
  tags:
    - base

- debug: var=emacs_version.stdout_lines
  when: test | default(false) | bool
  tags:
    - base

- debug: var=emacs_version.stdout.strip()
  when: test | default(false) | bool
  tags:
    - base

- name: base template
  template: src={{ item }}.j2 dest={{ test_path }}/{{ item }} backup=yes
  with_items:
    - shrc
    - bashrc
    - emacs
    - tmux.conf
  tags:
    - base

- name: copy base files
  copy: src={{ item }}  dest={{ test_path }}/{{ item }} backup=yes
  with_items:
    - env
    - vimrc
    - profile
    - screenrc
    - gitconfig
    - gitignore
    - pythonstartup
    - create.links.sh
  tags:
    - base

- name: copy desk files
  copy: src={{ item }}  dest={{ test_path }}/{{ item }} backup=yes
  with_items:
    - zshrc
    - Xdefaults
    - pentadactylrc
    - vimperatorrc
    - fonts.conf
  when: desk | default(false) | bool

## ansible default generate config mode : 660 -rw-rw-r--
- name: find ~/dotfiles -type f | xargs chmod 640
  shell: find ~/dotfiles -type f | xargs chmod 640

### XXX test NO BackUp task executed only specify option : -e "test=true"
#- name:  test config
#  template: src={{ item.src }} dest={{ item.dest }}
#  when: test | default(false) | bool
#  with_items:
#    - { src: hello.cfg.j2, dest: /root/hello.cfg }
#    - { src: hello.cfg.j2, dest: /root/hello.cfg }
