---
- name: mkdir -pv ~/dotfiles
  file: path=~/dotfiles state=directory

- name: ~/.profile
  template: src=profile.j2 dest={{ test_path }}/profile
  tags:
    - bash

- name: ~/.shrc
  template: src=shrc.j2  dest={{ test_path }}/shrc
  tags:
    - bash

- name: ~/.bashrc
  template: src=bashrc.j2  dest={{ test_path }}/bashrc
  tags:
    - bash

- name: ~/.vimrc
  template: src=vimrc.j2 dest={{ test_path }}/vimrc
  tags:
    - vim

- name: Check emacs verson
  shell: emacs --version|head -n 1|awk '{print $3}'
  register: emacs_version
  tags:
    - emacs

- debug: var=emacs_version.stdout_lines
  when: test | default(false) | bool
  tags:
    - emacs

- debug: var=emacs_version.stdout.strip()
  when: test | default(false) | bool
  tags:
    - emacs

- name: ~/.emacs
  template: src=emacs.j2 dest={{ test_path }}/emacs
  tags:
    - emacs

- name: Check tmux verson
  command: tmux -V
  register: tmux_version
  tags:
    - tmux

- name: Add as Fact for tmux version
  set_fact:
    version: "{{ tmux_version.stdout.strip().split()[1] }}"
  tags:
    - tmux

- debug: var=tmux_version.stdout_lines
  when: test | default(false) | bool
  #tags:
  #  - v
- debug: var=tmux_version.stdout.strip()
  when: test | default(false) | bool
  #tags:
  #  - v
- debug: var=tmux_version.stdout.strip().split()[1]
  when: test | default(false) | bool
  #tags:
  #  - v
- debug: var=version
  when: test | default(false) | bool
  #tags:
  #  - v

- name: ~/.tmux.conf
  template: src=tmux.conf.j2 dest={{ test_path }}/tmux.conf
  tags:
    - tmux

- name: ~/.pythonstartup
  copy: src=pythonstartup dest={{ test_path }}/pythonstartup
  tags:
    - pystartup

- name: ~/dotfiles/create.links.sh
  copy: src=create.links.sh dest={{ test_path }}/create.links.sh
  tags:
    - script

## ansible default generate config mode : 660 -rw-rw-r--
- name: find ~/dotfiles -type f | xargs chmod 640
  shell: find ~/dotfiles -type f | xargs chmod 640


### XXX test NO BackUp task executed only specify option : -e "test=true"
#- name:  test config
#  template: src={{ item.src }} dest={{ item.dest }}
#  when: test | default(false) | bool
#  with_items:
#    - { src: hello.cfg.j2, dest: /root/hello.cfg }
#    - { src: hello.cfg.j2, dest: /root/hello.cfg }
