## *login shells* only source one of : ~/.bash_profile or ~/.profile

## XXX NOT auto source ~/.profile
[[ -f ~/.profile ]] && . ~/.profile
[[ -f ~/.shrc ]] && . ~/.shrc
[[ -f /etc/bash_completion ]] && source /etc/bash_completion

## XXX login shell does NOT execute ~/.bashrc but only ~/.profile or ~/.bash_profile
[[ -f ~/.bashrc ]] && . ~/.bashrc
